[package]
name = "ftp-server-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.5"
libunftp = "0.20.1"
log = "0.4.22"
regex = "1.11.1"
tokio = { version = "1.41.1", features = ["full"] }
unftp-sbe-fs = "0.2.5"
